package constant

const (
	HUIWebPort                 = "H_UI_WEB_PORT"
	HUIWebContext              = "H_UI_WEB_CONTEXT"
	HUICrtPath                 = "H_UI_CRT_PATH"
	HUIKeyPath                 = "H_UI_KEY_PATH"
	JwtSecret                  = "JWT_SECRET"
	Hysteria2Enable            = "HYSTERIA2_ENABLE"
	Hysteria2Config            = "HYSTERIA2_CONFIG"
	Hysteria2TrafficTime       = "HYSTERIA2_TRAFFIC_TIME"
	Hysteria2ConfigRemark      = "HYSTERIA2_CONFIG_REMARK"
	Hysteria2ConfigPortHopping = "HYSTERIA2_CONFIG_PORT_HOPPING"
	Hysteria2Node2Enable       = "HYSTERIA2_NODE2_ENABLE"
	Hysteria2Node2Config       = "HYSTERIA2_NODE2_CONFIG"
	Hysteria2Node2Remark       = "HYSTERIA2_NODE2_REMARK"
	Hysteria2Socks5Addr        = "HYSTERIA2_SOCKS5_ADDR"
	Hysteria2Socks5User        = "HYSTERIA2_SOCKS5_USER"
	Hysteria2Socks5Pass        = "HYSTERIA2_SOCKS5_PASS"
	ResetTrafficCron           = "RESET_TRAFFIC_CRON"
	TelegramEnable             = "TELEGRAM_ENABLE"
	TelegramToken              = "TELEGRAM_TOKEN"
	TelegramChatId             = "TELEGRAM_CHAT_ID"
	TelegramDebug              = "TELEGRAM_DEBUG"
	TelegramLoginJobEnable     = "TELEGRAM_LOGIN_JOB_ENABLE"
	TelegramLoginJobText       = "TELEGRAM_LOGIN_JOB_TEXT"
	ClashExtension             = "CLASH_EXTENSION"
)
