name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Build binaries
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/*
        generate_release_notes: true
        body: |
          ## H UI 双节点支持版本
          
          ### 新功能
          - ✅ 双节点支持：配置第二节点通过主节点 SOCKS5 出站
          - ✅ 用户权限控制：为每个用户单独设置单节点或双节点权限
          - ✅ 智能订阅生成：根据用户权限动态生成订阅内容
          - ✅ 配置管理：完整的第二节点配置导入导出功能
          
          ### 安装方法
          ```bash
          bash <(curl -fsSL https://raw.githubusercontent.com/maxage/h-ui/main/install.sh)
          ```
          
          详细说明请查看：[DUAL_NODE_INSTALL.md](https://github.com/maxage/h-ui/blob/main/DUAL_NODE_INSTALL.md)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}